// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	grpc "github.com/Haba1234/coordinateStoradge/internal/grpc/api"
	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Start provides a mock function with given fields: addr
func (_m *Server) Start(addr string) error {
	ret := _m.Called(addr)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Server) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamDots provides a mock function with given fields: stream
func (_m *Server) StreamDots(stream grpc.Statistics_StreamDotsServer) error {
	ret := _m.Called(stream)

	var r0 error
	if rf, ok := ret.Get(0).(func(grpc.Statistics_StreamDotsServer) error); ok {
		r0 = rf(stream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
