// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	grpc "github.com/Haba1234/coordinateStoradge/internal/grpc/api"
	mock "github.com/stretchr/testify/mock"
)

// StatisticsServer is an autogenerated mock type for the StatisticsServer type
type StatisticsServer struct {
	mock.Mock
}

// StreamDots provides a mock function with given fields: _a0
func (_m *StatisticsServer) StreamDots(_a0 grpc.Statistics_StreamDotsServer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(grpc.Statistics_StreamDotsServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedStatisticsServer provides a mock function with given fields:
func (_m *StatisticsServer) mustEmbedUnimplementedStatisticsServer() {
	_m.Called()
}
