// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/Haba1234/coordinateStoradge/internal/grpc/api"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// StatisticsClient is an autogenerated mock type for the StatisticsClient type
type StatisticsClient struct {
	mock.Mock
}

// StreamDots provides a mock function with given fields: ctx, opts
func (_m *StatisticsClient) StreamDots(ctx context.Context, opts ...grpc.CallOption) (api.Statistics_StreamDotsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 api.Statistics_StreamDotsClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) api.Statistics_StreamDotsClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.Statistics_StreamDotsClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
